server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
        - id: fetchapi-service
          uri: http://localhost:8084
          predicates:
              - Path=/api/**
        - id: wishlist-service
          uri: http://localhost:8082
          predicates:
              - Path=/favourites/**